# -*- coding: utf-8 -*-
"""anuario_seguranca_publica_rj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9wgMXDDZAZD4gM70kGXhEs5mU3EBhgP

<img loading="lazy" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg" width="40" height="40"/> <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/pandas/pandas-original-wordmark.svg" width="40" height="40"/>   <img loading="lazy" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/plotly/plotly-original-wordmark.svg" width="40" height="40"/>

---

>
**Dev**: Gabriel Prata
>
**Data**: 01/03/2026
>
**Última modificação**: 22/03/2026
>
**Contexto**: *Dados abertos de segurança pública do Estado do Rio de Janeiro*
>
---

![Badge em Desenvolvimento](http://img.shields.io/static/v1?label=STATUS&message=EM%20DESENVOLVIMENTO&color=GREEN&style=for-the-badge)

![Badge versao](http://img.shields.io/static/v1?label=Ver.&message=v2.0&color=red&style=for-the-badge&logo=github)

#**<font color=#4c60d6 size="6"> Import libraries**
"""

# Importação de pacotes
import pandas as pd
import numpy as np
import missingno as ms # para tratamento de missings
import datetime
import re # expressão regulares
import unicodedata

#bibliotecas para visualização de dados
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.subplots import make_subplots

#compactar
from shutil import copyfileobj
import bz2
# Data e hora
from datetime import datetime, date, time

# Configuração para não exibir os warnings
import warnings
warnings.filterwarnings("ignore")

"""#**<font color=#4c60d6 size="6"> 1. Coleta de dados**"""

# importando dataset

# URL de importação
# Conjunto de dados com o registro das ocorrencias
url   = "https://raw.githubusercontent.com/gabrielmprata/Info_seguranca_publica_rj/main/datasets/BaseDPEvolucaoMensalCisp.csv.bz2"
df_ocorrencias = pd.read_csv(url, compression='bz2', encoding = "Latin 1", delimiter=';')

# Conjunto de dados com a unidade territorial das delegacias(CISP)
url2   = "https://raw.githubusercontent.com/gabrielmprata/Info_seguranca_publica_rj/main/datasets/CISP.csv"
df_cisp = pd.read_csv(url2, encoding = "Latin 1", delimiter=';')

"""---

#**<font color=#4c60d6 size="6"> 2. Análise de Dados Inicial**

###**<font color=#4c60d6> 2.1. Estatísticas Descritivas**

Compreende a organização, o resumo e, descrever os dados, que podem ser expressos em tabelas e gráficos.
>
Veremos a seguir alguns comandos para exibir algumas estatísticas descritivas.
"""

#	Quantidade de atributos e instâncias (linhas/colunas)
df_ocorrencias.shape

"""<font color=#4c60d6> Data frame com 65 atributos(features) e 37.314 tuplas.
>


---




"""

# Exibir os 5 primeiros registros
df_ocorrencias.head(5)

"""

---

"""

# Mostra diversas informações do Dataframe em um único comando, e exibir o uso de memória
df_ocorrencias.info(memory_usage="deep")

"""<font color=#4c60d6> Data frame utilizando 24.2 MB de memória.


---
"""

# Quantidade de valores únicos
df_ocorrencias.nunique()

"""

---

"""

# Quantidade de NaN/Missing/Nulls no dataframe
df_ocorrencias.isnull().sum()

"""---

###**<font color=#4c60d6> 2.2. Distribuição dos atributos**

>Nessa etapa, iremos verificar a distribuição dos principais atributos. Para ver se existe a necessidade de tomar alguma ação de transformações na etapa de preparação de dados.


---
"""

df_ocorrencias.describe().round(2)

"""---

> Distribuição para os principais atributos
"""

df_ocorrencias.cisp.value_counts(normalize=True)

df_ocorrencias.munic.value_counts(normalize=True)

df_ocorrencias.regiao.value_counts(normalize=True)

"""Por acaso, descobrimos um valor do atributo fora do padrão.
>
Iremos tratar na fase do Pré-processamento de dados.

#**<font color=#4c60d6 size="6"> 3. Pré-Processamento de dados**

Após coletar e analisar os dados na etapa anterior, agora é o momento
de limpar, transformar e apresentar melhor os dados.
>
Assim poderemos obter, na próxima etapa, os melhores resultados possíveis nos algoritmos de
Machine Learning, ou simplesmente apresentar dados mais confiáveis para os clientes em soluções de
business intelligence.


---

###**<font color=#4c60d6> 3.1. Limpeza**

De forma resumida, a limpeza consiste na verificação da consistência das informações, correção de possíveis erros de preenchimento ou eliminação de valores desconhecidos, redundantes ou não pertencentes ao domínio.

####**<font color=#4c60d6> 3.1.1 Redundâncias**

Vamos eliminar as colunas que não iremos utilizar em nossas analises.
>
A ideia é ter um dataframe mais leve, e com pouco espaço em disco.
"""

df_ocorrencias.drop([
				            'mes_ano','mcirc','fase'
                    ], axis=1, inplace= True)

df_cisp.drop([
				            'RISP','AISP'
                    ], axis=1, inplace= True)

"""####**<font color=#4c60d6> 3.1.2 Tratamento de Missings**

Como o DataFrame tem muitos atributos, e muitos deles possuem valores nulos, vou utlizar um método para mostrar apenas os valores nulos e o percentual.
>
1) Converter a função isnull() em um pd.series e depois transformar em DF, assim conseguimos filtrar quais atributos são nulos.
>
"""

#1)
# cria um pd.series
dfnull = df_ocorrencias.isnull().sum()

# Converte series em dataframe
dfnull = (dfnull.to_frame(name="QTD"))

tot = len(df_ocorrencias) #Total de registros no dataset

#Criano o atributo perc, para saber o percentual de registros nulo do atributo
dfnull["perc"] = ((dfnull['QTD']/tot)*100).round(2)

#Mostrar apenas os atributos com valores nulos, ordenando para o com mais linhas nulas
dfnull.query('QTD > 0').sort_values(by='perc', ascending=False)

"""2) Usar a librarie **MISSINGNO**, que retorna um avisão gráfica bem interessante."""

#A Barra mostra a quantidade de registros preenchidos
#Sort ordena do mais preenchido para o menos sort="ascending"
#Sem o sort="ascending", aparece pela ordem dos campos

ms.bar(df_ocorrencias, color="dodgerblue",  figsize=(20,15), fontsize=12)

"""Como todos os atributos são metricas, preenchido com a quatidade de ocorrencias registradas, iremos preencher todos com zero."""

df_ocorrencias['feminicidio'] = df_ocorrencias['feminicidio'].fillna(0)
df_ocorrencias['tentativa_feminicidio'] = df_ocorrencias['tentativa_feminicidio'].fillna(0)
df_ocorrencias['roubo_bicicleta'] = df_ocorrencias['roubo_bicicleta'].fillna(0)
df_ocorrencias['furto_bicicleta'] = df_ocorrencias['furto_bicicleta'].fillna(0)
df_ocorrencias['apf'] = df_ocorrencias['apf'].fillna(0)
df_ocorrencias['posse_drogas'] = df_ocorrencias['posse_drogas'].fillna(0)
df_ocorrencias['trafico_drogas'] = df_ocorrencias['trafico_drogas'].fillna(0)
df_ocorrencias['apreensao_drogas_sem_autor'] = df_ocorrencias['apreensao_drogas_sem_autor'].fillna(0)
df_ocorrencias['cmp'] = df_ocorrencias['cmp'].fillna(0)
df_ocorrencias['aaapai'] = df_ocorrencias['aaapai'].fillna(0)
df_ocorrencias['cmba'] = df_ocorrencias['cmba'].fillna(0)
df_ocorrencias['roubo_cx_eletronico'] = df_ocorrencias['roubo_cx_eletronico'].fillna(0)

ms.bar(df_ocorrencias, color="dodgerblue",  figsize=(20,15), fontsize=12)

"""####**<font color=#4c60d6> 3.1.3 Outliers**"""

import plotly.express as px

fig = px.box(df_ocorrencias, x='ano', y="total_furtos")
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo


fig.show()

df_ocorrencias[['cisp','ano','mes','munic',
                'furto_veiculos','furto_transeunte','furto_coletivo',
                'furto_celular','furto_bicicleta','outros_furtos']][(df_ocorrencias['total_furtos'] == 1665)]

df_ocorrencias[['cisp','ano','mes','munic','total_furtos',
                'furto_veiculos','furto_transeunte','furto_coletivo',
                'furto_celular','furto_bicicleta','outros_furtos']][(df_ocorrencias['cisp'] == 16) &
                                                                    (df_ocorrencias['ano'] == 2022)]

import plotly.express as px

fig = px.box(df_ocorrencias, x='ano', y="total_roubos")
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo


fig.show()

df_ocorrencias[['cisp','ano','mes','munic',
                'roubo_transeunte','roubo_celular','roubo_em_coletivo',
                'roubo_rua','roubo_veiculo','total_roubos']][(df_ocorrencias['total_roubos'] == 1160)]

df_ocorrencias[['cisp','ano','mes','munic',
                'roubo_transeunte','roubo_celular','roubo_em_coletivo',
                'roubo_rua','roubo_veiculo','total_roubos']][(df_ocorrencias['cisp'] == 64) &
                                                             (df_ocorrencias['ano'] == 2017)]

"""####**<font color=#4c60d6> 3.1.4 Padronização de dados**

Dentro da programação, possuímos alguns padrões de escrita para nomes de variáveis, funções, classes e assim por diante.
>
Esses padrões de escrita são chamados de estilos de case.
>
Existem diversos tipos de case, nesse projeto iremos utilizar:
>
**Snake Case (snake_case)**: Nesse estilo, todas as letras são minúsculas e as palavras são separadas por um underscore(_).
>
**Remover acentos (remover_acentos)**: Nesse estilo, todas as letras são minúsculas e as palavras são separadas por um underscore(_).

Nesse projeto somente o conjunto de dados de CISP, precisa de padronização de dados.

><font color=#4c60d6>**Conjunto de dados CISP**
"""

df_cisp.info()

def remover_acentos(texto):
    # Decompõe caracteres acentuados (ex: á -> a + ´)
    texto_normalizado = unicodedata.normalize('NFKD', texto)
    # Remove os caracteres de acentuação (intervalo unicode)
    return re.sub(r'[\u0300-\u036f]', '', texto_normalizado)

df_cisp.columns = [remover_acentos(column) for column in df_cisp.columns]
df_cisp.columns

# Criar uma função para aplicar o snake_case
def snake_case(string):
    string = re.sub(" +", " ", string)   # substitui múltiplos espaços por um espaço
    string = re.sub(" ", "_", string)    # substitui espaço por _
    return string.lower() # transforma em minuscula

df_cisp.columns = [snake_case(column) for column in df_cisp.columns]
df_cisp.columns

"""Substituir o separador dos valores de virgula para ponto e virgula"""

df_cisp['unidade_territorial'] = df_cisp['unidade_territorial'].str.replace(',',';', regex=True)

"""---

><font color=#4c60d6>**Atributo total de ocorrencias**

Para facilitar a escrita dos códigos, vou renoar o atributo **registro_ocorrencias**, que é o total de ocorrencias registradas, para **total**.
"""

# Renomear campos

df_ocorrencias = df_ocorrencias.rename(columns={'registro_ocorrencias': 'total'})

""">Atributo Região"""

df_ocorrencias.regiao.value_counts(normalize=True)

df_ocorrencias.loc[df_ocorrencias.regiao=='Grande NiterÃÂÃÂÃÂÃÂ³i','regiao']='Grande Niterói'

df_ocorrencias.regiao.value_counts(normalize=True)

"""####**<font color=#4c60d6> 3.1.5 Duplicidade de registros**"""

# Verificando se existe duplicidade na dimensão
df_cisp.duplicated(subset='cisp', keep='first').sum()

# Exibindo os registros duplicados
duplicidade = df_cisp['cisp'].duplicated(keep='first')
df_cisp[duplicidade]

# Detalhando um registro duplicado como exemplo
df_cisp.query('cisp == 108' )

# Removendo as duplicidades
df_cisp = df_cisp[~duplicidade]

# Validando se ainda existe duplicidade na dimensão
df_cisp.duplicated(subset='cisp', keep='first').sum()

"""---

###**<font color=#4c60d6> 3.2 Criação de recursos**

Também conhecida como ***feature engineering***, a criação de recursos consiste em criar, a partir dos atributos originais, um conjunto de atributos que capture informações importantes.

####**<font color=#4c60d6> 3.2.1 Construção de recuros**

><font color=#4c60d6>**Atributo data e hora**

Criar um atributo com o ano e o mês para facilitar as analises gráficas.
"""

df_ocorrencias['ano_mes'] = df_ocorrencias['ano'].map(str) + '-' + df_ocorrencias['mes'].map(str)
df_ocorrencias['ano_mes'] = pd.to_datetime(df_ocorrencias['ano_mes'])
df_ocorrencias['ano_mes'] = df_ocorrencias['ano_mes'].dt.strftime('%Y-%m')

"""><font color=#4c60d6>**Atributo mês em caracter**"""

# Mes em caracter
df_ocorrencias['mes_char'] = df_ocorrencias['mes']

dic_mes = {
1: 'Janeiro',
2: 'Fevereiro',
3: 'Março',
4: 'Abril',
5: 'Maio',
6: 'Junho',
7: 'Julho',
8: 'Agosto',
9: 'Setembro',
10: 'Outubro',
11: 'Novembro',
12: 'Dezembro'}

# Fazer o replace nos atributos conforme o dicionario
df_ocorrencias = df_ocorrencias.replace({
    'mes_char' : dic_mes
})

"""><font color=#4c60d6>**Atributo Regiões integradas de segurança pública (RISP)**"""

# RISP corresponência
df_ocorrencias['risp_desc'] = df_ocorrencias['risp']

dic_risp = {
1: 'Capital (Zona Sul, Centro e parte da Norte)',
2: 'Capital (Zona Oeste e parte da Norte)',
3: 'Baixada Fluminense',
4: 'Grande Niterói e Região dos Lagos',
5: 'Sul Fluminense',
6: 'Norte Fluminense e Noroeste',
7: 'Região Serrana'
}

# Fazer o replace nos atributos conforme o dicionario
df_ocorrencias = df_ocorrencias.replace({
    'risp_desc' : dic_risp
})

"""> Atributo com o total de policiais mortos em serviço"""

df_ocorrencias['pol_mortos_serv'] = df_ocorrencias['pol_militares_mortos_serv']+df_ocorrencias['pol_civis_mortos_serv']

"""####**<font color=#4c60d6> 3.2.2 Enriquecimento**

Existem outros atributos que iremos relacionar com outro dataset.
>
Seria como um modelo relacional, porém nesse caso, iremos adicionar no dataset principal(Fato), os atributos das dimensões.

><font color=#4c60d6>**Circunscrições Integradas de Segurança Pública  (CISP)**
"""

df_ocorrencias = pd.merge(df_ocorrencias, df_cisp, left_on=['cisp'], right_on=['cisp'], how='left')

"""###**<font color=#4c60d6> 3.3 Redução da dimensionalidade**

O dataset conta com informações de 2003 a 2026(parcial).
>
Vou construir um dataset para mostrar a evolução ao longo dos anos, e outro com os últimos 4 anos.

><font color=#4c60d6>**Por ano**
"""

df_hist_anual = df_ocorrencias[['ano','mes','mes_char','total','letalidade_violenta','hom_doloso','lesao_corp_morte','latrocinio','cvli','hom_por_interv_policial','feminicidio','pol_militares_mortos_serv','pol_civis_mortos_serv','total_roubos','total_furtos','roubo_carga','roubo_veiculo','roubo_rua','roubo_transeunte','roubo_celular','roubo_em_coletivo','estelionato','extorsao','apreensao_drogas','apf','aaapai']][(df_ocorrencias['ano'] <= 2025)]
df_hist_anual = df_hist_anual.groupby(['ano','mes','mes_char']).sum(['total','letalidade_violenta','hom_doloso','lesao_corp_morte','latrocinio','cvli','hom_por_interv_policial','feminicidio','pol_militares_mortos_serv','pol_civis_mortos_serv','total_roubos','total_furtos','roubo_carga','roubo_veiculo','roubo_rua','roubo_transeunte','roubo_celular','roubo_em_coletivo','estelionato','extorsao','apreensao_drogas','apf','aaapai']).reset_index()
# criar atributo com o total de policiais mortos em serviço
df_hist_anual['pol_mortos_serv'] = df_hist_anual['pol_militares_mortos_serv']+df_hist_anual['pol_civis_mortos_serv']

"""><font color=#4c60d6>**Comparação Por ano(todos)**"""

# Criar dataframe para comparar a variação ano contra ano (em K)
df_hs_compara = df_hist_anual.groupby('ano')[['letalidade_violenta','hom_doloso', 'total_roubos', 'roubo_veiculo', 'roubo_rua']].apply(lambda x: x.sum()).reset_index()

# Criar métrica com o valor do ano anterior
df_hs_compara['letalidade_violenta_ant'] = df_hs_compara.letalidade_violenta.shift(1)
df_hs_compara['hom_doloso_ant'] = df_hs_compara.hom_doloso.shift(1)
df_hs_compara['roubos_ant'] = df_hs_compara.total_roubos.shift(1)
df_hs_compara['roubo_veiculo_ant'] = df_hs_compara.roubo_veiculo.shift(1)
df_hs_compara['roubo_rua_ant'] = df_hs_compara.roubo_rua.shift(1)

# Variação em percentual
df_hs_compara['var_letalidade_violenta'] = (((df_hs_compara['letalidade_violenta']/df_hs_compara['letalidade_violenta_ant'])*100)-100).round(1)
df_hs_compara['var_hom_doloso'] = (((df_hs_compara['hom_doloso']/df_hs_compara['hom_doloso_ant'])*100)-100).round(1)
df_hs_compara['var_roubos'] = (((df_hs_compara['total_roubos']/df_hs_compara['roubos_ant'])*100)-100).round(1)
df_hs_compara['var_roubo_veiculo'] = (((df_hs_compara['roubo_veiculo']/df_hs_compara['roubo_veiculo_ant'])*100)-100).round(1)
df_hs_compara['var_roubo_rua'] = (((df_hs_compara['roubo_rua']/df_hs_compara['roubo_rua_ant'])*100)-100).round(1)

# Modificar a cor da barra quando negativo ou positiva
df_hs_compara['color_let'] = np.where(df_hs_compara['var_letalidade_violenta'] < 0,'#4c60d6', '#e8816e')
df_hs_compara['color_hom'] = np.where(df_hs_compara['var_hom_doloso'] < 0,'#4c60d6', '#e8816e')
df_hs_compara['color_roubo'] = np.where(df_hs_compara['var_roubos'] < 0,'#4c60d6', '#e8816e')
df_hs_compara['color_veic'] = np.where(df_hs_compara['var_roubo_veiculo'] < 0,'#4c60d6', '#e8816e')
df_hs_compara['color_rua'] = np.where(df_hs_compara['var_roubo_rua'] < 0,'#4c60d6', '#e8816e')

# Arredondamento em K para gráfico
df_hs_compara['letalidade_violenta'] = (df_hs_compara['letalidade_violenta']/1000).round(2)
df_hs_compara['hom_doloso'] = (df_hs_compara['hom_doloso']/1000).round(2)
df_hs_compara['total_roubos'] = (df_hs_compara['total_roubos']/1000).round(2)
df_hs_compara['roubo_veiculo'] = (df_hs_compara['roubo_veiculo']/1000).round(2)
df_hs_compara['roubo_rua'] = (df_hs_compara['roubo_rua']/1000).round(2)

"""><font color=#4c60d6>**Anuário**"""

df_anuario = df_ocorrencias[(df_ocorrencias['ano'] == 2025)].copy().reset_index()

"""><font color=#4c60d6>**Por região**"""

df_regiao_cisp = df_ocorrencias[['ano','risp','risp_desc','letalidade_violenta','roubo_carga','roubo_veiculo','roubo_rua']][(df_ocorrencias['ano'] >= 2024) & (df_ocorrencias['ano'] <= 2025) ]
df_regiao_cisp = df_regiao_cisp.groupby(['ano','risp','risp_desc']).sum(['letalidade_violenta','roubo_carga','roubo_veiculo','roubo_rua']).reset_index()

"""---

###**<font color=#4c60d6> 3.4 Export**

Agora iremos exportar o dataset em CSV, para usarmos no Streamlit
"""

# Exportar para csv
df_anuario.to_csv('df_anuario.csv', sep='|', encoding="Latin 1", index=False)

df_cisp.to_csv('df_cisp.csv', sep='|', encoding="Latin 1", index=False)

df_hist_anual.to_csv('df_hist_anual.csv', index=False)
df_hs_compara.to_csv('df_hs_compara.csv', index=False)

# compactar arquivo com nivel de compressão máxima
with open('df_anuario.csv', 'rb') as input:
    with bz2.BZ2File('df_anuario.csv.bz2', 'wb', compresslevel=9) as output:
        copyfileobj(input, output)

"""#**<font color=#4c60d6 size="6"> 4. Anuário de Segurança 2025**

><font color=#4c60d6>📈 **Contrução dos gráficos** 📊

###**<font color=#4c60d6> 4.1. Resumo dos principais indicadores**
"""

# agrupa por ano
df_ind_anual = df_hist_anual[['ano','total','letalidade_violenta','hom_doloso','lesao_corp_morte','latrocinio','feminicidio','hom_por_interv_policial','total_roubos','total_furtos','estelionato','apreensao_drogas','pol_militares_mortos_serv','pol_mortos_serv']][(df_hist_anual['ano'] >= 2024)]
df_ind_anual = df_ind_anual.groupby('ano')[['total','letalidade_violenta','hom_doloso','lesao_corp_morte','latrocinio','feminicidio','hom_por_interv_policial','total_roubos','total_furtos','estelionato','apreensao_drogas','pol_militares_mortos_serv','pol_mortos_serv']].apply(lambda x: x.sum()).reset_index()

df_hs_ind_anual = df_hist_anual.groupby('ano')[['total','letalidade_violenta','hom_doloso','lesao_corp_morte','latrocinio','feminicidio','hom_por_interv_policial','total_roubos','total_furtos','estelionato','apreensao_drogas','pol_militares_mortos_serv','pol_mortos_serv']].apply(lambda x: x.sum()).reset_index()
df_hs_ind_anual

fig = go.Figure()

fig.add_trace(go.Indicator(
    mode = "number+delta",
    number={'valueformat': 's'},
    value = float(df_ind_anual.total.values[1]),
    delta = {"reference": int(df_ind_anual.total.values[0]), 'relative': True, "valueformat": ".1%",'increasing': {'color': "red"},'decreasing': {'color': "green"}},
    title = {"text": "Ocorrências" },
    domain = {'row': 0, 'column': 0}))

fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    mode = "number+delta",
    value = int(df_ind_anual.letalidade_violenta.values[1]),
    delta = {"reference": int(df_ind_anual.letalidade_violenta.values[0]),'relative': True, "valueformat": ".1%",'increasing': {'color': "red"},'decreasing': {'color': "green"}},
    title = {"text": "Letalidade Violenta" },
    domain = {'row': 0, 'column': 1}))

fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    mode = "number+delta",
    value = int(df_ind_anual.hom_doloso.values[1]),
    delta = {"reference": int(df_ind_anual.hom_doloso.values[0]),'increasing': {'color': "red"},'decreasing': {'color': "green"}},
    title = {"text": "Homicídio doloso" },
    domain = {'row': 1, 'column': 0}))

fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    mode = "number+delta",
    value = int(df_ind_anual.latrocinio.values[1]),
    delta = {"reference": int(df_ind_anual.latrocinio.values[0]),'increasing': {'color': "red"},'decreasing': {'color': "green"}},
    title = {"text": "Latrocínio" },
    domain = {'row': 1, 'column': 1}))

fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    mode = "number+delta",
    value = int(df_ind_anual.feminicidio.values[1]),
    delta = {"reference": int(df_ind_anual.feminicidio.values[0]),'increasing': {'color': "red"},'decreasing': {'color': "green"}},
    title = {"text": "Feminicídios" },
    domain = {'row': 2, 'column': 0}))

fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    mode = "number+delta",
    value = int(df_ind_anual.total_roubos.values[1]),
    delta = {"reference": int(df_ind_anual.total_roubos.values[0]),'relative': True, "valueformat": ".1%",'increasing': {'color': "red"},'decreasing': {'color': "green"}},
    title = {"text": "Roubos" },
    domain = {'row': 2, 'column': 1}))

fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    mode = "number+delta",
    value = int(df_ind_anual.apreensao_drogas.values[1]),
    delta = {"reference": int(df_ind_anual.apreensao_drogas.values[0]), 'relative': True, "valueformat": ".1%", 'increasing': {'color': "green"},'decreasing': {'color': "red"}},
    title = {"text": "Apreensão de drogas" },
    domain = {'row': 3, 'column': 0}))

fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    mode = "number+delta",
    value = int(df_ind_anual.pol_mortos_serv.values[1]),
    delta = {"reference": int(df_ind_anual.pol_mortos_serv.values[0]),'increasing': {'color': "red"},'decreasing': {'color': "green"}},
    title = {"text": "Policiais mortos em serviço" },
    domain = {'row': 3, 'column': 1}))

fig.update_layout(
    paper_bgcolor = "lightgray",
    width=650, height = 800,
    grid = {'rows': 4, 'columns': 2, 'pattern': "independent"},
    )

"""**Na comparação ANO contra ANO, tivemos os principais resultados:**
>
Os **registros de ocorrências** tiveram um aumento de 4.6% em relação a 2024, cerca de 42k registros a mais nas delegacias de polícia.
>
O indicador **Letalidade Violenta**, que corresponde à soma das vítimas de homicídio doloso, Morte por Intervenção de Agente do Estado, roubo seguido de morte (Latrocínio) e lesão corporal seguida de morte, apresentou aumento de 1,9%, 70 casos a mais.
>
O ano de 2025 registrou 70 casos a menos de **homicídio doloso** (quando há intenção de matar), e o crime de **latrocínio** (roubo seguido de morte) teve uma queda de 22 casos, contabilizando 77 vítimas.
>
Já o número de **feminicídios**, não é possível comparar com o ano anterior, pois o dataset disponibilizado pelo ISP, está incompleto para 2024(apenas 3 meses de registros).
Em 2025 foram registrados 104 **feminicídios** e 307 **tentativas desse delito**.
>
Os registros de **roubo** apresentaram uma queda de 8.6%, uma redução de 9.207 registros desse delito.
>
Destaca-se, nessa categoria, a queda de **9.4%** no indicador de **roubo de carga**.
Os indicadores **Roubo de Rua e Roubo de Veículo** registraram quedas de 2,7% e 18,4%, respectivamente.
>
Tivemos um aumento de 7.9% na **apreensão de drogas**, 1.901 registros a mais em relação ao ano anterior.

---

###**<font color=#4c60d6> 4.2 Registros de ocorrencias**

####**<font color=#4c60d6> 4.2.1 Registros de ocorrencias por ano**
"""

df_hist_ano = df_hist_anual.groupby(['ano'])['total'].sum().reset_index()
df_hist_ano['total'] = ((df_hist_ano['total'])/1000).round(1)

fig = px.line(df_hist_ano, x='ano', y='total',
              markers=True, line_shape="spline", template="plotly_dark", render_mode="svg",
              text="total", title = "Ocorrências por ano",
              height=525, #altura
              width=850,  #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", total = "Ocorrencias (k)")
              )
fig.update_layout(xaxis = dict(linecolor='rgba(0,0,0,1)', tickmode = 'array', tickvals = df_hist_anual['ano'], ticktext = df_hist_anual['ano']))
fig.add_annotation(
    x=2020,        # Coordenada X onde a seta aponta
    y=584.99,               # Coordenada Y onde a seta aponta
    font=dict(color="red", size=12),
    text="Covid-19", # Texto da anotação
    showarrow=True,     # Mostrar seta
    arrowhead=2,        # Estilo da ponta da seta
    ax=-50,               # Posição X do texto em relação à seta (px)
    ay=0              # Posição Y do texto em relação à seta (px)
)
fig.update_traces(textposition="top center")
fig.show()

"""As delegacias contabilizaram 965.208 **registros de ocorrências**.
>
Apresentando um aumento de 4.6% em relação a 2024.
>
Vale destacar que esse indicador aumenta nos últimos 5 anos.
>
Uma observação importante é a queda brusca de registros nos anos de 2020 e 2021, quando tivemos a **pandemia de Covid-19**.

####**<font color=#4c60d6> 4.2.2 Mapa de calor das ocorrencias**
"""

# Dataframe agrupando por dia da semana e hora
df_hot_ocor = df_hist_anual.groupby(['ano','mes', 'mes_char'])['total'].sum().reset_index()

fig = px.density_heatmap(df_hot_ocor.sort_values(['ano', 'mes' ], ascending=[True, True] ),
                         x="mes_char",
                         y="ano",
                         z="total",
                         histfunc="sum", text_auto=True,
                         #labels=dict(mes="Mês"),
                         labels=dict(mes_char="Mês",  ano="Ano"),
                         color_continuous_scale="RdYlBu_r",template="plotly_dark"
                         )

fig.layout['coloraxis']['colorbar']['title'] = 'Ocorrências'
#fig.update_traces(dict(colorscale='RdYlBu_r',showscale=True,coloraxis=None),)
fig.update_yaxes(type="category") # se o type for date, vai respeitar o intervalo
fig.update_xaxes(type="category") # se o type for date, vai respeitar o intervalo
fig.show()

"""####**<font color=#4c60d6> 4.2.3 Registros de ocorrencias por mês**"""

df_mes = df_hist_anual[(df_hist_anual['ano'] == 2025)].groupby(['mes','mes_char'])['total'].sum().reset_index()

fig = px.bar(df_mes, x='mes_char', y='total',
              template="plotly_dark",
              height=250, #altura
              #width=850,  #largura
              text="total", text_auto=True,
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(mes_char="Mês", total = "Ocorrências")
              )

fig.update_xaxes(showticklabels=True, showgrid=False, title=None)
fig.update_yaxes(showticklabels=False, showgrid=False)

fig.show()

# média do ano de 2025
df_mes['total'].mean()

# média por dia de 2025
((df_mes['total'].sum())/365).round(0)

"""No ano de 2025 tivemos uma média de 80.434 registros de ocorrências por mês, e uma média de 2.644 por dia.
>
O mês com mais registros foi **março**, 84.129, possivelmente por conta do carnaval.

####**<font color=#4c60d6> 4.2.4 Por Região**

As **Regiões Integradas de Segurança Pública (RISP)** são organizadas, a nível prático, com base nas divisões das Áreas Integradas de Segurança Pública (AISP) e Circunscrições Integradas de Segurança Pública (CISP), que são equivalentes à área de um batalhão da Polícia Militar e de uma delegacia da Polícia Civil, respectivamente.
"""

df_tot_reg = df_anuario[(df_anuario['ano'] == 2025)].groupby(['risp_desc'])['total'].sum().reset_index()

fig = px.pie(df_tot_reg, values='total', names='risp_desc', hole=0.5,
             labels=dict(total="Ocorrências", risp_desc="Região"),
             template="plotly_dark",
             color_discrete_sequence=px.colors.sequential.Blues_r
             )
fig.show()

"""####**<font color=#4c60d6> 4.2.5 Por Município**"""

df_tot_munic = (df_anuario[(df_anuario['ano'] == 2025)].groupby(['munic'])['total'].sum().reset_index()).sort_values(by='total', ascending=False).head(10)

fig = go.Figure(data=[go.Table(

    header=dict(values=['Município', 'Total'],
                fill_color='royalblue',
                align='left'),
    cells=dict(values=[df_tot_munic.munic, df_tot_munic.total],
               fill_color='lightskyblue',
               align='center',
               font = dict(color = 'darkslategray', size = 11)
               ))
],layout=go.Layout(template="plotly_dark"))

fig.show()

"""####**<font color=#4c60d6> 4.2.6 Por Delegacia**"""

df_tot_dp = (df_anuario[(df_anuario['ano'] == 2025)].groupby(['risp_desc','cisp','unidade_territorial'])['total'].sum().reset_index()).sort_values(by='total', ascending=False).head(10)

fig = go.Figure(data=[go.Table(

    header=dict(values=['RISP', 'Delegacia', 'Unidade', 'Total'],
                fill_color='royalblue',
                align='left'),
    cells=dict(values=[df_tot_dp.risp_desc, df_tot_dp.cisp, df_tot_dp.unidade_territorial, df_tot_dp.total],
               fill_color='lightskyblue',
               align='center',
               font = dict(color = 'darkslategray', size = 11)
               ))
],layout=go.Layout(template="plotly_dark"))

fig.show()

"""###**<font color=#4c60d6> 4.3 Crimes contra a vida**

Esta seção expõe os dados referentes ao indicador de **Letalidade Violenta** e o perfil de suas vítimas, além das informações sobre a vitimização policial em 2025
"""

fig = go.Figure()
fig.add_trace(go.Indicator(mode = "number+delta", number={'valueformat': 's'}, value = float(df_ind_anual.letalidade_violenta.values[1]),
    delta = {"reference": int(df_ind_anual.letalidade_violenta.values[0]), 'relative': True, "valueformat": ".1%",'increasing': {'color': "red"},'decreasing': {'color': "green"}},
    title = {"text": "Letalidade Violenta"},
    domain = {'row': 0, 'column': 0}))

fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    value = int((df_ind_anual.letalidade_violenta.values[1]/365).round(0)),
    title = {"text": "Vítimas média por dia" },
    domain = {'row': 0, 'column': 1}))

fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    mode = "number+delta",
    value = int(df_ind_anual.hom_doloso.values[1]),
    delta = {"reference": int(df_ind_anual.hom_doloso.values[0]),'increasing': {'color': "red"},'decreasing': {'color': "green"}},
    title = {"text": "Homicídio doloso" },
    domain = {'row': 1, 'column': 0}))

fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    mode = "number+delta",
    value = int(df_ind_anual.latrocinio.values[1]),
    delta = {"reference": int(df_ind_anual.latrocinio.values[0]),'increasing': {'color': "red"},'decreasing': {'color': "green"}},
    title = {"text": "Latrocínio" },
    domain = {'row': 1, 'column': 1}))
##
fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    mode = "number+delta",
    value = int(df_ind_anual.lesao_corp_morte.values[1]),
    delta = {"reference": int(df_ind_anual.lesao_corp_morte.values[0]),'increasing': {'color': "red"},'decreasing': {'color': "green"}},
    title = {"text": "Lesão corporal<br> seguida de morte" },
    domain = {'row': 2, 'column': 0}))

fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    mode = "number+delta",
    value = int(df_ind_anual.hom_por_interv_policial.values[1]),
    delta = {"reference": int(df_ind_anual.hom_por_interv_policial.values[0]),'relative': True, "valueformat": ".1%",'increasing': {'color': "red"},'decreasing': {'color': "green"}},
    title = {"text": "Morte por Intervenção<br> de Agente do Estado" },
    domain = {'row': 2, 'column': 1}))

fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    mode = "number+delta",
    value = int(df_ind_anual.feminicidio.values[1]),
    delta = {"reference": int(df_ind_anual.feminicidio.values[0]), 'relative': True, "valueformat": ".1%", 'increasing': {'color': "green"},'decreasing': {'color': "red"}},
    title = {"text": "Feminicídios" },
    domain = {'row': 3, 'column': 0}))

fig.add_trace(go.Indicator(
    number={'valueformat': 's'},
    mode = "number+delta",
    value = int(df_ind_anual.pol_mortos_serv.values[1]),
    delta = {"reference": int(df_ind_anual.pol_mortos_serv.values[0]),'increasing': {'color': "red"},'decreasing': {'color': "green"}},
    title = {"text": "Policiais mortos em serviço" },
    domain = {'row': 3, 'column': 1}))

fig.update_layout(
    paper_bgcolor = "darkblue", font = {'color': "white", 'family': "Arial"},
    width=650, height = 800,
    grid = {'rows': 4, 'columns': 2, 'pattern': "independent"},
    )

"""####**<font color=#4c60d6> 4.3.1 Letalidade Violenta**

Composto pelos delitos de **homicídio doloso, morte por intervenção de agente do estado, roubo seguido de morte (Latrocínio) e lesão corporal seguida de morte.**

---
"""

# Criar dataframe para comparar a variação ano contra ano (em K)
df_hs_compara = df_hist_anual.groupby('ano')[['letalidade_violenta','hom_doloso', 'total_roubos', 'roubo_veiculo', 'roubo_rua']].apply(lambda x: x.sum()).reset_index()

# Criar métrica com o valor do ano anterior
df_hs_compara['letalidade_violenta_ant'] = df_hs_compara.letalidade_violenta.shift(1)
df_hs_compara['hom_doloso_ant'] = df_hs_compara.hom_doloso.shift(1)
df_hs_compara['roubos_ant'] = df_hs_compara.total_roubos.shift(1)
df_hs_compara['roubo_veiculo_ant'] = df_hs_compara.roubo_veiculo.shift(1)
df_hs_compara['roubo_rua_ant'] = df_hs_compara.roubo_rua.shift(1)

# Variação em percentual
df_hs_compara['var_letalidade_violenta'] = (((df_hs_compara['letalidade_violenta']/df_hs_compara['letalidade_violenta_ant'])*100)-100).round(1)
df_hs_compara['var_hom_doloso'] = (((df_hs_compara['hom_doloso']/df_hs_compara['hom_doloso_ant'])*100)-100).round(1)
df_hs_compara['var_roubos'] = (((df_hs_compara['total_roubos']/df_hs_compara['roubos_ant'])*100)-100).round(1)
df_hs_compara['var_roubo_veiculo'] = (((df_hs_compara['roubo_veiculo']/df_hs_compara['roubo_veiculo_ant'])*100)-100).round(1)
df_hs_compara['var_roubo_rua'] = (((df_hs_compara['roubo_rua']/df_hs_compara['roubo_rua_ant'])*100)-100).round(1)

# Modificar a cor da barra quando negativo ou positiva
df_hs_compara['color_let'] = np.where(df_hs_compara['var_letalidade_violenta'] < 0,'#4c60d6', '#e8816e')
df_hs_compara['color_hom'] = np.where(df_hs_compara['var_hom_doloso'] < 0,'#4c60d6', '#e8816e')
df_hs_compara['color_roubo'] = np.where(df_hs_compara['var_roubos'] < 0,'#4c60d6', '#e8816e')
df_hs_compara['color_veic'] = np.where(df_hs_compara['var_roubo_veiculo'] < 0,'#4c60d6', '#e8816e')
df_hs_compara['color_rua'] = np.where(df_hs_compara['var_roubo_rua'] < 0,'#4c60d6', '#e8816e')

# Arredondamento em K para gráfico
df_hs_compara['letalidade_violenta'] = (df_hs_compara['letalidade_violenta']/1000).round(2)
df_hs_compara['hom_doloso'] = (df_hs_compara['hom_doloso']/1000).round(2)
df_hs_compara['total_roubos'] = (df_hs_compara['total_roubos']/1000).round(2)
df_hs_compara['roubo_veiculo'] = (df_hs_compara['roubo_veiculo']/1000).round(2)
df_hs_compara['roubo_rua'] = (df_hs_compara['roubo_rua']/1000).round(2)

fig = px.line(df_hs_compara, x='ano', y='letalidade_violenta',
              markers=True, text='letalidade_violenta',
              #height=600, width=800, #altura x largura
              line_shape="spline",
              template="plotly_dark",
              render_mode="svg",
              title = "Letalidade Violenta por Ano",
              labels=dict(ano="Ano", letalidade_violenta="Letalidade Violenta(k)")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_traces(line_width=2,textposition='top center')
fig.show()

fig2 = px.bar(df_hs_compara, x="ano", y="var_letalidade_violenta", title = "Diferença YxY(%)", template="plotly_dark", text_auto=True,
              #height=300, width=1160,  #largura
              labels=dict(ano="Ano", var_letalidade_violenta='Variação')#, hover_data=['ano', 'dif','var']
              )
fig2.update_traces(textangle=0, textfont_size=12, textposition='outside', cliponaxis=False, marker_color=df_hs_compara["color_let"])
fig2.update_yaxes(showticklabels=False, showgrid=False,visible=False, fixedrange=True)
fig2.update_xaxes(showgrid=False,visible=False, fixedrange=True, type="category", title=None)


fig2.show()

"""O indicador de **Letalidade Violenta** registrou, em 2025, 3.881 vítimas (um aumento de 1,9% em relação ao ano anterior)."""

fig = px.line(df_anuario.groupby(['mes', 'mes_char'])['letalidade_violenta'].sum().reset_index(), x='mes_char', y=['letalidade_violenta'],
              markers=True, text='value',line_shape="spline",template="plotly_dark",
              title = "Letalidade Violenta por mês", color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(mes_char="Mês", value="Letalidade", variable="Letalidade")
              )
fig.update_xaxes(type="category", title=None)
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')
fig.show()

"""**Outubro** foi o mês com mais registros de letalidade violenta no estado no ano de 2025.

---

><font color=#4c60d6>**Análise individual dos delitos que compõem a Letalidade Violenta**

####**<font color=#4c60d6> 4.3.2 Homicídio doloso**
"""

fig = px.line(df_hs_compara, x='ano', y='hom_doloso',
              markers=True, text='hom_doloso',
              #height=600, width=800, #altura x largura
              line_shape="spline",
              template="plotly_dark",
              render_mode="svg",
              title = "Homicídio doloso por Ano",
              labels=dict(ano="Ano", hom_doloso="Homicídio (k)")
              )
fig.update_xaxes(type="category", title=None)
fig.update_traces(line_width=2,textposition='top center')
fig.show()

fig2 = px.bar(df_hs_compara, x="ano", y="var_hom_doloso", title = "Diferença YxY(%)", template="plotly_dark", text_auto=True,
              #height=300, width=1160,  #largura
              labels=dict(ano="Ano", var_hom_doloso='Variação')#, hover_data=['ano', 'dif','var']
              )
fig2.update_traces(textangle=0, textfont_size=12, textposition='outside', cliponaxis=False, marker_color=df_hs_compara["color_hom"])
fig2.update_yaxes(showticklabels=False, showgrid=False,visible=False, fixedrange=True)
fig2.update_xaxes(showgrid=False,visible=False, fixedrange=True, type="category", title=None)


fig2.show()

"""Destacamos que o estado registrou 2.833 vítimas de **homicídio doloso**, representando uma **queda de 2.48%**, menos setenta e duas vítimas se comparado com 2024."""

fig = px.line(df_anuario.groupby(['mes', 'mes_char'])['hom_doloso'].sum().reset_index(), x='mes_char', y=['hom_doloso'],
              markers=True, text='value',
              #height=600, width=800, #altura x largura
              line_shape="spline",
              template="plotly_dark",
              render_mode="svg",
              title = "Homicídio doloso por mês",
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(mes_char="Mês", value="Homicídio", variable="Homicídio")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""**Janeiro** foi o mês com mais registros de homicídio culposo no estado no ano de 2025.

---

**<font color=#4c60d6> Homicídio doloso por RISP**
"""

fig = px.pie(df_anuario.groupby(['risp_desc'])['hom_doloso'].sum().reset_index(), values='hom_doloso', names='risp_desc',
             hole=0.5,
             template="plotly_dark",
             color_discrete_sequence=px.colors.sequential.Blues_r,
             labels=dict(hom_doloso="Homicídio", risp_desc="RISP")
             )
fig.show()

"""A Baixada Fluminense é a região que mais registrou homicídios, foram 779, correspondendo a 27.5% do Estado.

---

**<font color=#4c60d6> Homicídio por município mais ofensor**
"""

df_homiciodio_mun = df_anuario.groupby(['regiao','munic'])['hom_doloso'].sum().reset_index()
df_homiciodio_mun =  df_homiciodio_mun.sort_values(by='hom_doloso', ascending=False).head(10)

fig = go.Figure(data=[go.Table(

    header=dict(values=['Região','Município', 'Total'],
                fill_color='royalblue',
                align='left'),
    cells=dict(values=[df_homiciodio_mun.regiao, df_homiciodio_mun.munic, df_homiciodio_mun.hom_doloso],
               fill_color='lightskyblue',
               align='center',
               font = dict(color = 'darkslategray', size = 11)
               ))
],layout=go.Layout(template="plotly_dark"))

fig.show()

"""**<font color=#4c60d6> Homicídio por CISP e unidade territorial**"""

df_homiciodio_un = (df_anuario.groupby(['risp_desc','cisp','unidade_territorial'])['hom_doloso'].sum().reset_index()
).sort_values(by='hom_doloso', ascending=False).head(10)

fig = go.Figure(data=[go.Table(

    header=dict(values=['RISP','Delagacia', 'Unidade Territorial', 'Total'],
                fill_color='royalblue',
                align='left'),
    cells=dict(values=[df_homiciodio_un.risp_desc, df_homiciodio_un.cisp, df_homiciodio_un.unidade_territorial, df_homiciodio_un.hom_doloso],
               fill_color='lightskyblue',
               align='center',
               font = dict(color = 'darkslategray', size = 11)
               ))
],layout=go.Layout(template="plotly_dark"))

fig.show()

"""A delegacia que mais registrou homicídios, está localizada na Baixada Fluminense, e atende as localidades de:
>
Posse
>
Austin
>
Miguel Couto
>
Vila de Cava
>
Tinguá

---

####**<font color=#4c60d6> 4.3.3 Roubos seguido de morte (latrocínio)**
"""

fig = px.line(df_hist_anual.groupby(['ano'])['latrocinio'].sum().reset_index(), x='ano', y=['latrocinio'],
              markers=True, text='value',line_shape="spline",template="plotly_dark",
              title = "Latrocínio doloso por mês",
              height=525, width=850, #altura #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", value="Latrocínio", variable="Latrocínio")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""Foram 77 vítimas de roubos seguido de morte (latrocínio) no estado, apresentando uma queda de 22 casos no número de vítimas em relação ao ano anterior."""

fig = px.line(df_anuario.groupby(['mes', 'mes_char'])['latrocinio'].sum().reset_index(), x='mes_char', y=['latrocinio'],
              markers=True, text='value',
              #height=600, width=800, #altura x largura
              line_shape="spline",
              template="plotly_dark",
              render_mode="svg",
              title = "Latrocínio por mês",
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(mes_char="Mês", value="Latrocínio", variable="Latrocínio")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""No mês de **dezembro** foram registrados 13 casos, um aumento de 117% em relação ao mês anterior.

####**<font color=#4c60d6> 4.3.4 Lesão corporal seguida de morte**
"""

fig = px.line(df_hist_anual.groupby(['ano'])['lesao_corp_morte'].sum().reset_index(), x='ano', y=['lesao_corp_morte'],
              markers=True, text='value',line_shape="spline",template="plotly_dark",
              title = "lesão corporal seguida de morte por ano",
              height=525, width=850, #altura #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", value="lesão corporal", variable="lesão corporal")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""O crime de lesão corporal seguida de morte contabilizou 67 vítimas, 2 casos a menos em relacão ao ano anterior."""

fig = px.line(df_anuario.groupby(['mes', 'mes_char'])['lesao_corp_morte'].sum().reset_index(), x='mes_char', y=['lesao_corp_morte'],
              markers=True, text='value',
              #height=600, width=800, #altura x largura
              line_shape="spline",
              template="plotly_dark",
              render_mode="svg",
              title = "lesão corporal seguida de morte por mês",
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(mes_char="Mês", value="lesão corporal", variable="lesão corporal")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""Os meses com mais casos foram Janeiro e Março, e no final do ano vemos uma queda de 67% nesse delito.

####**<font color=#4c60d6> 4.3.5 Mortes por Intervenção de Agente do Estado**
"""

fig = px.line(df_hist_anual.groupby(['ano'])['hom_por_interv_policial'].sum().reset_index(), x='ano', y=['hom_por_interv_policial'],
              markers=True, text='value',line_shape="spline",template="plotly_dark",
              title = "Mortes por Intervenção de Agente do Estado por ano",
              height=525, width=850, #altura #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", value="Mortes", variable="Mortes")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""As Mortes por Intervenção de Agente do Estado subiram 13,4% (797 no total do ano) em relação a 2024, que havia registrado 703 vítimas.

---
"""

fig = px.line(df_anuario.groupby(['mes', 'mes_char'])['hom_por_interv_policial'].sum().reset_index(), x='mes_char', y=['hom_por_interv_policial'],
              markers=True, text='value',
              #height=600, width=800, #altura x largura
              line_shape="spline",
              template="plotly_dark",
              render_mode="svg",
              title = "Mortes por Intervenção de Agente do Estado por mês",
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(mes_char="Mês", value="Mortes", variable="Mortes")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""No mês de **Outubro** foram registrados 175 casos desse delito, um aumento de 250% em relação ao mês anterior.
>
No dia 28/10, ocorreu uma operação policial nos complexos do Alemão e da Penha, onde 121 pessoas morreram e 113 foram presas.
>
De acordo com a Polícia Civil, dentre os 121 mortos, 4 eram policiais.
>

"""

fig = px.density_heatmap(df_hist_anual.groupby(['ano','mes','mes_char'])['hom_por_interv_policial'].sum().reset_index().sort_values(['ano', 'mes' ], ascending=[True, True] ),
                         x="mes_char", y="ano", z="hom_por_interv_policial",
                         histfunc="sum", text_auto=True,
                         labels=dict(mes_char="Mês",  ano="Ano", hom_por_interv_policial="Mortos"),
                         color_continuous_scale="RdYlBu_r",template="plotly_dark"
                         )

fig.layout['coloraxis']['colorbar']['title'] = 'Mortes'
fig.update_yaxes(type="category")
fig.update_xaxes(type="category")
fig.show()

"""**<font color=#4c60d6> Homicídio por CISP e unidade territorial**"""

df_interv_un = (df_anuario.groupby(['risp_desc','cisp','unidade_territorial'])['hom_por_interv_policial'].sum().reset_index()
).sort_values(by='hom_por_interv_policial', ascending=False).head(10)

fig = go.Figure(data=[go.Table(

    header=dict(values=['RISP','Delagacia', 'Unidade Territorial', 'Total'],
                fill_color='royalblue',
                align='left'),
    cells=dict(values=[df_interv_un.risp_desc, df_interv_un.cisp, df_interv_un.unidade_territorial, df_interv_un.hom_por_interv_policial],
               fill_color='lightskyblue',
               align='center',
               font = dict(color = 'darkslategray', size = 11)
               ))
],layout=go.Layout(template="plotly_dark"))

fig.show()

"""####**<font color=#4c60d6> 4.3.6 Vitimização policial**

O dataset disponibilizado pelo ISP, só divulga o número de policias mortos em serviço.
"""

fig = px.line(df_hist_anual.groupby(['ano'])['pol_mortos_serv'].sum().reset_index(), x='ano', y=['pol_mortos_serv'],
              markers=True, text='value',line_shape="spline",template="plotly_dark",
              title = "Policiais mortos em serviço",
              height=525, width=850, #altura #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", value="Mortes", variable="Mortes")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""Destacamos o aumento no número de policiais mortos que cresceu 58,3% em comparação com o ano de 2024.

---
"""

fig = px.line(df_anuario.groupby(['mes', 'mes_char'])['pol_mortos_serv'].sum().reset_index(), x='mes_char', y=['pol_mortos_serv'],
              markers=True, text='value',
              #height=600, width=800, #altura x largura
              line_shape="spline",
              template="plotly_dark",
              render_mode="svg",
              title = "Policiais mortos em serviço",
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(mes_char="Mês", value="Mortes", variable="Mortes")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

""">**<font color=#4c60d6>Considerando a separação entre Polícia Militar e Polícia Civil**"""

fig = px.bar(df_hist_anual.groupby('ano')[['pol_mortos_serv','pol_militares_mortos_serv','pol_civis_mortos_serv']].apply(lambda x: x.sum()).reset_index(),
             x="ano", y=['pol_militares_mortos_serv','pol_civis_mortos_serv'],
             labels=dict(pol_militares_mortos_serv="Polícial Militar", pol_civis_mortos_serv="Policial Civil", ano="Ano", value="Mortes", variable="Categoria"),
             color_discrete_sequence=px.colors.sequential.Blues_r,
             template="plotly_dark", text_auto=''
             )
fig.update_layout(legend=dict(
    yanchor="top",
    y=-0.15,
    xanchor="left",
    x=0
))
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig.update_xaxes(type="category", title=None)
fig.show()

"""###**<font color=#4c60d6> 4.4 Crimes contra o patrimônio**

Exibiremos aqui os indicadores de **Roubo de Carga, Roubo de Veículo e Roubo de Rua** (este último engloba os crimes de **roubo a transeunte, roubo de celular e roubo a coletivo**).
>
Desde 2021, acrescentamos os dados referentes ao **estelionato e extorsão**, devido ao crescimento significativo que vem apresentando nos últimos anos.

####**<font color=#4c60d6> 4.4.1 Roubo**

Esse indicador engloba todos os delitos de: roubo a transeunte, roubo de celular, roubo em coletivo, roubo de rua, roubo de veiculo, roubo de carga,
roubo de comercio, roubo de residência, roubo de banco, roubo de caixa eletrônico, roubo condução saque
roubo apos saque, roubo bicicleta e outros roubos.
"""

fig = px.line(df_hs_compara, x='ano', y='total_roubos', title = "Roubos por Ano",
              markers=True, text='total_roubos', line_shape="spline", template="plotly_dark",
              labels=dict(ano="Ano", letalidade_violenta="Roubos(k)")
              )
fig.update_xaxes(type="category", title=None)
fig.update_traces(line_width=2,textposition='top center')
fig.show()

fig2 = px.bar(df_hs_compara, x="ano", y="var_roubos", title = "Diferença YxY(%)", template="plotly_dark", text_auto=True,
              #height=300, width=1160,  #largura
              labels=dict(ano="Ano", var_roubos='Variação')#, hover_data=['ano', 'dif','var']
              )
fig2.update_traces(textangle=0, textfont_size=12, textposition='outside', cliponaxis=False, marker_color=df_hs_compara["color_roubo"])
fig2.update_yaxes(showticklabels=False, showgrid=False,visible=False, fixedrange=True)
fig2.update_xaxes(showgrid=False,visible=False, fixedrange=True, type="category", title=None)
fig2.show()

fig = px.line(df_anuario.groupby(['mes', 'mes_char'])['total_roubos'].sum().reset_index(),
              x='mes_char', y=['total_roubos'],
              markers=True, text='value',
              #height=600, width=800, #altura x largura
              line_shape="spline",
              template="plotly_dark",
              render_mode="svg",
              title = "Roubos por mês",
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(mes_char="Mês", value="Roubos", variable="Roubos")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""O mês com mais registros de ocorrências de roubos, foram Janeiro e Dezembro.
>
Sendo que de Novembro para Dezembro tivemos um aumento de 22%.

---

**<font color=#4c60d6> Roubos por CISP e unidade territorial**
"""

df_roubo_un = (df_anuario.groupby(['risp_desc','cisp','unidade_territorial'])['total_roubos'].sum().reset_index()
).sort_values(by='total_roubos', ascending=False).head(10)

fig = go.Figure(data=[go.Table(

    header=dict(values=['RISP','Delagacia', 'Unidade Territorial', 'Total'],
                fill_color='royalblue',
                align='left'),
    cells=dict(values=[df_roubo_un.risp_desc, df_roubo_un.cisp, df_roubo_un.unidade_territorial, df_roubo_un.total_roubos],
               fill_color='lightskyblue',
               align='center',
               font = dict(color = 'darkslategray', size = 11)
               ))
],layout=go.Layout(template="plotly_dark"))

fig.show()

"""A delegacia com mais registros de roubos no estado, é a 59 DP, que atende a região de Duque de Caxias.

####**<font color=#4c60d6> 4.4.2 Roubo de carga**
"""

fig = px.line(df_hist_anual.groupby('ano')[['roubo_carga']].apply(lambda x: x.sum()/1000).round(2).reset_index(),
              x='ano', y='roubo_carga',
              markers=True, text='roubo_carga',line_shape="spline",template="plotly_dark",
              title = "Roubo de Carga",
              height=525, width=850, #altura #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", roubo_carga = "Roubos (k)")
              )
fig.update_xaxes(type="category", title=None)
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""Em 2025, ocorreram **3.114 casos de Roubo de Carga**, representando uma diminuição de **9,4%** em relação ao ano anterior.

####**<font color=#4c60d6> 4.4.3 Roubo de Veículo**
"""

fig = px.line(df_hs_compara, x='ano', y='roubo_veiculo', title = "Roubos de Veículos por Ano",
              markers=True, text='roubo_veiculo', line_shape="spline", template="plotly_dark",
              labels=dict(ano="Ano", roubo_veiculo="Roubos(k)")
              )
fig.update_layout(xaxis = dict(linecolor='rgba(0,0,0,1)', tickmode = 'array', tickvals = df_hs_compara['ano'], ticktext = df_hs_compara['ano']))
fig.update_xaxes(title=None)
fig.update_traces(line_width=2,textposition='top center')
fig.add_annotation(x=2020, y=25.42, font=dict(color="red", size=12), text="Covid-19", showarrow=True, arrowhead=2, ax=-50, ay=0)
fig.show()

fig2 = px.bar(df_hs_compara, x="ano", y="var_roubo_veiculo", title = "Diferença YxY(%)", template="plotly_dark", text_auto=True,
              labels=dict(ano="Ano", var_roubo_veiculo='Variação')
              )
fig2.update_traces(textangle=0, textfont_size=12, textposition='outside', cliponaxis=False, marker_color=df_hs_compara["color_veic"])
fig2.update_yaxes(showticklabels=False, showgrid=False,visible=False, fixedrange=True)
fig2.update_xaxes(showgrid=False,visible=False, fixedrange=True, title=None)
fig2.show()

"""O ano de 2025 registrou uma queda de **18,4%** nos casos de **Roubo de Veículo**.
>
Observamos um aumento significativo nesses casos entre 2015 e 2017, seguido por uma queda brusca até 2020.
>
O número se manteve estável até 2022 e encerrou a série com uma nova queda observada em 2025.

**Nota: Vale lembrar que 2020 e 2021 foram anos da pandemia de Covid-19.**

####**<font color=#4c60d6> 4.4.4 Roubo de Rua**
"""

fig = px.line(df_hs_compara, x='ano', y='roubo_rua', title = "Roubos de Rua por Ano",
              markers=True, text='roubo_rua', line_shape="spline", template="plotly_dark",
              labels=dict(ano="Ano", roubo_veiculo="Roubos(k)")
              )
fig.update_layout(xaxis = dict(linecolor='rgba(0,0,0,1)', tickmode = 'array', tickvals = df_hs_compara['ano'], ticktext = df_hs_compara['ano']))
fig.update_xaxes(title=None)
fig.update_traces(line_width=2,textposition='top center')
fig.add_annotation(x=2020, y=71.95, font=dict(color="red", size=12), text="Covid-19", showarrow=True, arrowhead=2, ax=-50, ay=0)
fig.show()

fig2 = px.bar(df_hs_compara, x="ano", y="var_roubo_rua", title = "Diferença YxY(%)", template="plotly_dark", text_auto=True,
              #height=300, width=1160,  #largura
              labels=dict(ano="Ano", roubo_rua='Variação')#, hover_data=['ano', 'dif','var']
              )
fig2.update_traces(textangle=0, textfont_size=12, textposition='outside', cliponaxis=False, marker_color=df_hs_compara["color_rua"])
fig2.update_yaxes(showticklabels=False, showgrid=False,visible=False, fixedrange=True)
fig2.update_xaxes(showgrid=False,visible=False, fixedrange=True, type="category", title=None)
fig2.show()

"""O indicador de Roubo de Rua vinha apresentando queda dos casos desde 2018.
>
Em 2023, registrou-se o menor número de ocorrências desde 2004.
>
Já em 2025, apresentou um **decréscimo de 2,7%** em relação ao ano anterior.

####**<font color=#4c60d6> 4.4.5 Roubo a transeunte**
"""

fig = px.line(df_hist_anual.groupby('ano')[['roubo_transeunte']].apply(lambda x: x.sum()/1000).round(2).reset_index(),
              x='ano', y='roubo_transeunte',
              markers=True, text='roubo_transeunte',line_shape="spline",template="plotly_dark",
              title = "Roubo a transeunte",
              height=525, width=850, #altura #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", roubo_transeunte = "Roubos (k)")
              )
fig.update_layout(xaxis = dict(linecolor='rgba(0,0,0,1)', tickmode = 'array', tickvals = df_hist_anual['ano'], ticktext = df_hist_anual['ano']))
fig.add_annotation(
    x=2020,        # Coordenada X onde a seta aponta
    y=46.29,               # Coordenada Y onde a seta aponta
    font=dict(color="red", size=12),
    text="Covid-19", # Texto da anotação
    showarrow=True,     # Mostrar seta
    arrowhead=2,        # Estilo da ponta da seta
    ax=-50,               # Posição X do texto em relação à seta (px)
    ay=0              # Posição Y do texto em relação à seta (px)
)
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""Em 2025, o roubo a transeunte registrou **queda de 10,6%** casos, mantendo a tendência observada nos últimos anos.

####**<font color=#4c60d6> 4.4.6 Roubo de celular**
"""

fig = px.line(df_hist_anual.groupby('ano')[['roubo_celular']].apply(lambda x: x.sum()/1000).round(2).reset_index(),
              x='ano', y='roubo_celular',
              markers=True, text='roubo_celular',line_shape="spline",template="plotly_dark",
              title = "Roubo de celular",
              height=525, width=850, #altura #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", roubo_celular = "Roubos (k)")
              )
fig.update_layout(xaxis = dict(linecolor='rgba(0,0,0,1)', tickmode = 'array', tickvals = df_hist_anual['ano'], ticktext = df_hist_anual['ano']))
fig.add_annotation(
    x=2020,        # Coordenada X onde a seta aponta
    y=16.44,               # Coordenada Y onde a seta aponta
    font=dict(color="red", size=12),
    text="Covid-19", # Texto da anotação
    showarrow=True,     # Mostrar seta
    arrowhead=2,        # Estilo da ponta da seta
    ax=-50,               # Posição X do texto em relação à seta (px)
    ay=0              # Posição Y do texto em relação à seta (px)
)
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""Desde 2013, esse delito apresentava um crescimento constante, interrompido em 2020.
>
Ao final da pandemia, observamos uma queda nos números nos anos seguintes, mas, em 2024, os dados apresentaram nova crescente.
>
Em 2025, foram registrados **25.625** casos de **roubo de celular**, representando um aumento de **19,7%** em comparação com o ano anterior.
"""

fig = px.line(df_anuario.groupby(['mes', 'mes_char'])['roubo_celular'].sum().reset_index(), x='mes_char', y=['roubo_celular'],
              markers=True, text='value',
              #height=600, width=800, #altura x largura
              line_shape="spline",
              template="plotly_dark",
              render_mode="svg",
              title = "Roubo de celular por mês",
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(mes_char="Mês", value="Roubos", variable="Roubos")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""No mês de março foram registrados **2469** roubo de celulares, pois nesse mês temos a celebração do carnaval no estado.

####**<font color=#4c60d6> 4.4.7 Roubo em coletivo**
"""

fig = px.line(df_hist_anual.groupby('ano')[['roubo_em_coletivo']].apply(lambda x: x.sum()/1000).round(2).reset_index(),
              x='ano', y='roubo_em_coletivo',
              markers=True, text='roubo_em_coletivo',line_shape="spline",template="plotly_dark",
              title = "Roubo em coletivo",
              height=525, width=850, #altura #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", roubo_em_coletivo = "Roubos (k)")
              )
fig.update_layout(xaxis = dict(linecolor='rgba(0,0,0,1)', tickmode = 'array', tickvals = df_hist_anual['ano'], ticktext = df_hist_anual['ano']))
fig.add_annotation(
    x=2020,        # Coordenada X onde a seta aponta
    y=9.23,               # Coordenada Y onde a seta aponta
    font=dict(color="red", size=12),
    text="Covid-19", # Texto da anotação
    showarrow=True,     # Mostrar seta
    arrowhead=2,        # Estilo da ponta da seta
    ax=-50,               # Posição X do texto em relação à seta (px)
    ay=0              # Posição Y do texto em relação à seta (px)
)
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""Em 2025, o roubo em coletivo registrou um decréscimo em relação ao ano anterior de **40,6%**.

####**<font color=#4c60d6> 4.4.8 Estelionato**
"""

fig = px.line(df_hist_anual.groupby('ano')[['estelionato']].apply(lambda x: x.sum()/1000).round(1).reset_index(),
              x='ano', y='estelionato',
              markers=True, text='estelionato',line_shape="spline",template="plotly_dark",
              title = "Estelionato",
              height=525, width=850, #altura #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", estelionato = "Casos (k)")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""O estelionato foi incluído neste relatório devido ao aumento identificado nos últimos anos.
>
Em 2025 houve um aumento de **2,0%**, superando o ano anterior e somando o maior número de casos da série histórica.

####**<font color=#4c60d6> 4.4.9 Extorção**
"""

fig = px.line(df_hist_anual.groupby(['ano'])['extorsao'].sum().reset_index(),
              x='ano', y=['extorsao'],
              markers=True, text='value',line_shape="spline",template="plotly_dark",
              title = "Extorção",
              height=525, width=850, #altura #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", value="Casos", variable="Casos")
              )
fig.update_xaxes(type="category", title=None)
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')

fig.show()

"""Em 2025, tivemos **3.646** registros de extorsão, **19,5%** a mais do que em 2024 .

###**<font color=#4c60d6> 4.5 Atividade policial**

####**<font color=#4c60d6> 4.5.1 Apreensão de drogas**
"""

fig = px.line(df_hist_anual.groupby('ano')[['apreensao_drogas']].apply(lambda x: x.sum()/1000).round(1).reset_index(),
              x='ano', y='apreensao_drogas',
              markers=True, text='apreensao_drogas',line_shape="spline",template="plotly_dark",
              title = "Apreensão de drogas",
              height=525, width=850, #altura #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", apreensao_drogas = "Apreensão (k)")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')
fig.show()

"""As apreensões de drogas em 2025 tiveram um aumento de **7,9%** em relação ano anterior, mantendo a tendência de crescimento registrada nos últimos dois anos.

####**<font color=#4c60d6> 4.5.2 Prisão em flagrante**
"""

fig = px.line(df_hist_anual.groupby('ano')[['apf']].apply(lambda x: x.sum()/1000).round(1).reset_index(),
              x='ano', y='apf',
              markers=True, text='apf',line_shape="spline",template="plotly_dark",
              title = "Prisões em flagrante",
              height=525, width=850, #altura #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", apreensao_drogas = "Prisões (k)")
              )
fig.update_xaxes(type="category", title=None) # se o type for date, vai respeitar o intervalo
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')
fig.show()

"""Em 2025, foram registradas 42.295 prisões em flagrante em todo o estado, representando uma diminuição de 0,2% em relação ao ano anterior.
>
Em 2020, o número de prisões diminuiu devido às restrições de mobilidade impostas pela pandemia. No entanto, nos últimos anos, observamos uma tendência de aumento que se manteve até 2024, período em que obteve o maior número de toda a série.

####**<font color=#4c60d6> 4.5.3 Auto de apreensão de adolescente por prática de ato infracional**
"""

fig = px.line(df_hist_anual.groupby('ano')[['aaapai']].apply(lambda x: x.sum()/1000).round(1).reset_index(),
              x='ano', y='aaapai',
              markers=True, text='aaapai',line_shape="spline",template="plotly_dark",
              title = "Auto de apreensão de adolescente",
              height=525, width=850, #altura #largura
              color_discrete_sequence=px.colors.sequential.Blackbody_r,
              labels=dict(ano="Ano", aaapai = "Autos (k)")
              )
fig.update_xaxes(type="category", title=None)
fig.update_layout(showlegend=False)
fig.update_traces(line_width=2,textposition='top center')
fig.show()

"""Desde 2013, observamos uma queda no número de autos de apreensão de adolescentes por prática de ato infracional.
>
Em 2025, houve registro de 5.232 casos, um **crescimento de 6,4%** no número de adolescentes apreendidos em relação ao ano anterior.

###**<font color=#4c60d6> 4.6 Relatório RISP**

As **Regiões Integradas de Segurança Pública (RISP)** são organizadas, a nível prático, com base nas divisões das Áreas Integradas de Segurança Pública (AISP) e Circunscrições Integradas de Segurança Pública (CISP), que são equivalentes à área de um batalhão da Polícia Militar e de uma delegacia da Polícia Civil, respectivamente.

Ao todo, o estado possui sete RISP, divididas da seguinte maneira:
>
**RISP 1:** Capital (Zona Sul, Centro e parte da Zona Norte);
>
**RISP 2:** Capital (Zona Oeste e parte da Zona Norte);
>
**RISP 3:** Baixada Fluminense;
>
**RISP 4:** Grande Niterói e Região dos Lagos;
>
**RISP 5:** Sul Fluminense;
>
**RISP 6:** Norte-Fluminense e Noroeste;
>
**RISP 7:** Região Serrana.

####**<font color=#4c60d6> 4.6.1 Indicadores nas RISP**

>**<font color=#4c60d6>Indicadores de Roubo de Rua**
"""

fig = px.histogram(df_regiao_cisp, x="ano", y="roubo_rua", color='risp', barmode='group',
             labels=dict(risp="RISP", ano="Ano", roubo_rua="Roubos"),

             color_discrete_sequence=px.colors.sequential.Blues_r, text_auto='.3s',
             template="plotly_dark"
             )
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig.update_layout(yaxis_title="Roubos")
fig.update_layout(showlegend=False)
fig.show()

fig = px.histogram(df_regiao_cisp, x="risp", y="roubo_rua", color='ano', barmode='group',
             labels=dict(risp="RISP", ano="Ano", roubo_rua="Roubos"),
             color_discrete_sequence=px.colors.sequential.Blues_r, text_auto='.3s',
             template="plotly_dark"
             )
fig.update_xaxes(type="category", title=None)
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig.update_layout(yaxis_title="Roubos")
fig.update_layout(showlegend=True)
fig.show()

"""O indicador Roubo de Rua apresentou queda em seis das sete RISP: 1, 3, 4, 5, 6 e 7, em relação ao ano anterior.
>
 A maior redução foi observada na RISP 5, com 35,7% (148), enquanto a menor redução ocorreu na RISP 1, com 1,9% (20.734) dos roubos de rua em relação a 2024.
 >
  Já a RISP 2 apresentou um crescimento, foram 7,5% (17.495) casos.

>**<font color=#4c60d6>Indicadores de Roubo de Veículo**
"""

fig = px.histogram(df_regiao_cisp, x="ano", y="roubo_veiculo", color='risp', barmode='group',
             labels=dict(risp="RISP", ano="Ano", roubo_veiculo="Roubos"),

             color_discrete_sequence=px.colors.sequential.Blues_r, text_auto='.3s',
             template="plotly_dark"
             )
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig.update_layout(yaxis_title="Roubos")
fig.update_layout(showlegend=False)
fig.show()

"""Quatro das sete RISP do estado apresentaram queda nos casos de **Roubo de Veículo** em 2025, sendo as RISP 5 e 1 com as maiores reduções: **40,7% (54 casos no ano)** e **39,3% (4.951)**.
>
A menor redução foi observada na RISP 2, que diminuiu **4,1% (8.762)**.
>
As RISP 7, 6 e 4, por sua vez, tiveram aumento nos casos. Descatamos aqui a RISP 7 com **40,7% (38 casos)** e a RISP 6 com **32,8% (170 casos)**.

>**<font color=#4c60d6>Indicadores de Roubo de Carga**
"""

fig = px.histogram(df_regiao_cisp, x="ano", y="roubo_carga", color='risp', barmode='group',
             labels=dict(risp="RISP", ano="Ano", roubo_carga="Roubos"),

             color_discrete_sequence=px.colors.sequential.Blues_r, text_auto='.3s',
             template="plotly_dark"
             )
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig.update_layout(yaxis_title="Roubos")
fig.update_layout(showlegend=False)
fig.show()

"""As RISP 5 e 7 apresentaram as maiores quedas nos casos de Roubos de Carga.
>
Já a RISP 4 manteve-se estável, com o mesmo número de casos do ano anterior.

>**<font color=#4c60d6>Indicadores de Letalidade Violenta**
"""

fig = px.histogram(df_regiao_cisp, x="ano", y="letalidade_violenta", color='risp', barmode='group',
             labels=dict(risp="RISP", ano="Ano", letalidade_violenta="Casos"),

             color_discrete_sequence=px.colors.sequential.Blues_r, text_auto='.3s',
             template="plotly_dark"
             )
fig.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig.update_layout(yaxis_title="Casos")
fig.update_layout(showlegend=False)
fig.show()

"""O indicador **Letalidade Violenta** apresentou redução em quatro das sete RISP do estado.
>
A maior redução em 2025, em relação ao ano anterior, foi observada na RISP 4, com **11,1% (515 no total).**
>
Em contrapartida, a RISP 1 mostrou um crescimento de **23,3% (546)** do número de casos em 2025.
"""